const numberFromEnv = (key, fallback) => {
  const value = Number(process.env[key]);
  return Number.isFinite(value) && value > 0 ? value : fallback;
};

export const routeRecommendationConfig = {
  MAX_ORIGIN_STOPS: numberFromEnv('ROUTE_RECOMMENDATION_MAX_ORIGIN_STOPS', 8),
  MAX_DESTINATION_STOPS: numberFromEnv('ROUTE_RECOMMENDATION_MAX_DESTINATION_STOPS', 8),
  MAX_WALKING_DISTANCE_METERS: numberFromEnv('ROUTE_RECOMMENDATION_MAX_WALKING_DISTANCE_METERS', 1200),
  MAX_TRANSFER_WALKING_DISTANCE_METERS: numberFromEnv('ROUTE_RECOMMENDATION_MAX_TRANSFER_WALKING_DISTANCE_METERS', 600),
  MAX_TRANSFER_CANDIDATES_PER_STATION: numberFromEnv('ROUTE_RECOMMENDATION_MAX_TRANSFER_CANDIDATES_PER_STATION', 6),
  MAX_TRANSFER_ALIGHT_OPTIONS_PER_ORIGIN: numberFromEnv('ROUTE_RECOMMENDATION_MAX_TRANSFER_ALIGHT_OPTIONS_PER_ORIGIN', 12),
  MAX_TRANSFERS: numberFromEnv('ROUTE_RECOMMENDATION_MAX_TRANSFERS', 1),
  MAX_RECOMMENDATIONS: numberFromEnv('ROUTE_RECOMMENDATION_MAX_RECOMMENDATIONS', 5),
  TRANSFER_PENALTY_MINUTES: numberFromEnv('ROUTE_RECOMMENDATION_TRANSFER_PENALTY_MINUTES', 4),
  DEFAULT_BUS_SEGMENT_MINUTES: numberFromEnv('ROUTE_RECOMMENDATION_DEFAULT_BUS_SEGMENT_MINUTES', 5),
  DEFAULT_HEADWAY_MINUTES: numberFromEnv('ROUTE_RECOMMENDATION_DEFAULT_HEADWAY_MINUTES', 20),
  FALLBACK_WALKING_SPEED_METERS_PER_SECOND: numberFromEnv('ROUTE_RECOMMENDATION_FALLBACK_WALKING_SPEED_MPS', 1.25),
  WALKING_OSRM_BASE_URL: process.env.ROUTE_RECOMMENDATION_WALKING_OSRM_BASE_URL || 'https://router.project-osrm.org',
  WALKING_OSRM_PROFILE: process.env.ROUTE_RECOMMENDATION_WALKING_OSRM_PROFILE || 'foot',
  WALKING_OSRM_TIMEOUT_MS: numberFromEnv('ROUTE_RECOMMENDATION_WALKING_OSRM_TIMEOUT_MS', 3500),
};

export default routeRecommendationConfig;
