import express from 'express';
import ShiftController from './ShiftController.js';

const router = express.Router();

router.get('/shifts', ShiftController.listShifts);
router.post('/shifts', ShiftController.createShift);
router.post('/shifts/auto-generate', ShiftController.autoGenerateDailySchedule);
router.post('/shifts/confirm-generated', ShiftController.confirmGeneratedShifts);
router.get('/shifts/available-drivers', ShiftController.listAvailableDrivers);
router.get('/shifts/available-assistants', ShiftController.listAvailableAssistants);
router.get('/shifts/available-vehicles', ShiftController.listAvailableVehicles);
router.post('/shifts/:shiftId/assign-driver', ShiftController.assignDriverToSelectedShift);
router.post('/shifts/:shiftId/assign-assistant', ShiftController.assignAssistantToSelectedShift);
router.post('/shifts/:shiftId/assign-vehicle', ShiftController.assignVehicleToSelectedShift);
router.post('/shifts/:shiftId/assign-trip', ShiftController.assignTripToSelectedShift);
router.get('/shifts/:shiftId/assignments', ShiftController.listShiftAssignments);
router.put('/shifts/:shiftId', ShiftController.updateShift);
router.delete('/shifts/:shiftId', ShiftController.archiveShift);
router.get('/shift-assignments', ShiftController.listAssignments);
router.post('/shift-assignments/drivers', ShiftController.assignDriver);
router.post('/shift-assignments/vehicles', ShiftController.assignVehicle);
router.post('/shift-assignments/trips', ShiftController.assignTrip);

export default router;
