import ShiftService from './ShiftService.js';
import AutoGenerateShiftService from './AutoGenerateShiftService.js';
import logger from '../../utils/logger.js';

export default class ShiftController {
  static async listShifts(req, res, next) {
    try {
      const shifts = await ShiftService.listShifts(req.query);
      return res.json({ success: true, message: 'Tải danh sách ca làm việc thành công', shifts });
    } catch (error) {
      logger.error('List shifts error:', error);
      next(error);
    }
  }

  static async createShift(req, res, next) {
    try {
      const payload = ShiftService.normalizeShiftPayload(req.body, req.user?.userId);
      payload.createdBy = req.user?.userId;
      const errors = ShiftService.validateShiftPayload(payload);
      if (errors.length) return res.status(400).json({ success: false, message: errors[0], errors });
      const shift = await ShiftService.createShift(payload);
      return res.status(201).json({ success: true, message: 'Tạo ca làm việc thành công', shift });
    } catch (error) {
      logger.error('Create shift error:', error);
      if (error.code === 11000) {
        return res.status(409).json({ success: false, message: 'Mã ca đã tồn tại.' });
      }
      next(error);
    }
  }

  static async autoGenerateDailySchedule(req, res, _next) {
    try {
      const isPreviewRequest = req.body?.generationMode === 'PREVIEW'
        || Boolean(req.body?.routeId && (req.body?.startDate || req.body?.endDate));
      if (isPreviewRequest) {
        const preview = await AutoGenerateShiftService.generatePreview(req.body);
        return res.json({ success: true, generationMode: 'PREVIEW', message: 'Đã tạo danh sách ca tạm thời.', ...preview });
      }
      const requestDays = Number(req.body?.days || req.query?.days || 7);
      const generator = requestDays === 1
        ? ShiftService.autoGenerateDailySchedule
        : ShiftService.autoGenerateWeeklySchedule;
      const result = await generator.call(ShiftService, {
        workDate: req.body?.workDate || req.body?.date || req.query?.workDate || req.query?.date,
        actorId: req.user?.userId,
      });
      return res.status(201).json({ success: true, message: 'Sinh lich ca lam viec thanh cong', ...result });
    } catch (error) {
      logger.error('Auto generate shift schedule error:', error);
      return res.status(error.statusCode || 500).json({ success: false, message: error.message || 'Sinh lich ca lam viec that bai' });
    }
  }

  static async confirmGeneratedShifts(req, res, _next) {
    try {
      const result = await AutoGenerateShiftService.confirmGenerated({
        rows: req.body?.rows,
        actorId: req.user?.userId,
      });
      return res.status(201).json({ success: true, message: 'Đã lưu danh sách ca chính thức.', ...result });
    } catch (error) {
      logger.error('Confirm generated shifts error:', error);
      return res.status(error.statusCode || 500).json({
        success: false,
        message: error.message || 'Không thể lưu danh sách ca.',
        conflicts: error.conflicts || [],
      });
    }
  }

  static async listAvailableDrivers(req, res, _next) {
    return ShiftController.listAvailableResources(req, res, 'drivers');
  }

  static async listAvailableAssistants(req, res, _next) {
    return ShiftController.listAvailableResources(req, res, 'assistants');
  }

  static async listAvailableVehicles(req, res, _next) {
    return ShiftController.listAvailableResources(req, res, 'vehicles');
  }

  static async listAvailableResources(req, res, kind) {
    try {
      const resources = await AutoGenerateShiftService.listAvailableResources({ kind, ...req.query });
      return res.json({ success: true, resources });
    } catch (error) {
      logger.error(`List available ${kind} error:`, error);
      return res.status(error.statusCode || 500).json({ success: false, message: error.message || 'Không thể tải tài nguyên khả dụng.' });
    }
  }

  static async updateShift(req, res, next) {
    try {
      const payload = ShiftService.normalizeShiftPayload(req.body, req.user?.userId);
      const errors = ShiftService.validateShiftPayload(payload);
      if (errors.length) return res.status(400).json({ success: false, message: errors[0], errors });
      const shift = await ShiftService.updateShift(req.params.shiftId, payload);
      if (!shift) return res.status(404).json({ success: false, message: 'Không tìm thấy ca làm việc.' });
      return res.json({ success: true, message: 'Cập nhật ca làm việc thành công', shift });
    } catch (error) {
      logger.error('Update shift error:', error);
      if (error.code === 11000) {
        return res.status(409).json({ success: false, message: 'Mã ca đã tồn tại.' });
      }
      next(error);
    }
  }

  static async archiveShift(req, res, next) {
    try {
      const shift = await ShiftService.deactivateShift(req.params.shiftId, req.user?.userId);
      if (!shift) return res.status(404).json({ success: false, message: 'Không tìm thấy ca làm việc.' });
      return res.json({ success: true, message: 'Lưu trữ ca làm việc thành công', shift });
    } catch (error) {
      logger.error('Archive shift error:', error);
      next(error);
    }
  }

  static async listAssignments(req, res, next) {
    try {
      const assignments = await ShiftService.listAssignments(req.query);
      return res.json({ success: true, message: 'Tải phân công ca làm việc thành công', ...assignments });
    } catch (error) {
      logger.error('List shift assignments error:', error);
      next(error);
    }
  }

  static async listShiftAssignments(req, res, _next) {
    try {
      const assignments = await ShiftService.listAssignmentsForShift(req.params.shiftId);
      return res.json({ success: true, message: 'Tai phan cong ca lam viec thanh cong', ...assignments });
    } catch (error) {
      logger.error('List assignments for shift error:', error);
      return res.status(error.statusCode || 500).json({ success: false, message: error.message || 'Tai phan cong ca that bai' });
    }
  }

  static async assignDriverToSelectedShift(req, res, _next) {
    try {
      const assignment = await ShiftService.assignDriverToShift(req.params.shiftId, { ...req.body, actorId: req.user?.userId });
      return res.status(201).json({ success: true, message: 'Phan cong tai xe vao ca thanh cong', assignment });
    } catch (error) {
      logger.error('Assign driver to selected shift error:', error);
      return res.status(error.statusCode || 500).json({ success: false, message: error.message || 'Phan cong tai xe that bai' });
    }
  }

  static async assignAssistantToSelectedShift(req, res, _next) {
    try {
      const assignment = await ShiftService.assignAssistantToShift(req.params.shiftId, { ...req.body, actorId: req.user?.userId });
      return res.status(201).json({ success: true, message: 'Phan cong phu xe vao ca thanh cong', assignment });
    } catch (error) {
      logger.error('Assign assistant to selected shift error:', error);
      return res.status(error.statusCode || 500).json({ success: false, message: error.message || 'Phan cong phu xe that bai' });
    }
  }

  static async assignVehicleToSelectedShift(req, res, _next) {
    try {
      const assignment = await ShiftService.assignVehicleToShift(req.params.shiftId, { ...req.body, actorId: req.user?.userId });
      return res.status(201).json({ success: true, message: 'Phan cong xe vao ca thanh cong', assignment });
    } catch (error) {
      logger.error('Assign vehicle to selected shift error:', error);
      return res.status(error.statusCode || 500).json({ success: false, message: error.message || 'Phan cong xe that bai' });
    }
  }

  static async assignTripToSelectedShift(req, res, _next) {
    try {
      const assignment = await ShiftService.assignTripToShift(req.params.shiftId, { ...req.body, actorId: req.user?.userId });
      return res.status(201).json({ success: true, message: 'Phan cong chuyen vao ca thanh cong', assignment });
    } catch (error) {
      logger.error('Assign trip to selected shift error:', error);
      return res.status(error.statusCode || 500).json({ success: false, message: error.message || 'Phan cong chuyen that bai' });
    }
  }

  static async assignDriver(req, res, _next) {
    try {
      const assignment = await ShiftService.assignDriver({ ...req.body, actorId: req.user?.userId });
      return res.status(201).json({ success: true, message: 'Phân công tài xế vào ca thành công', assignment });
    } catch (error) {
      logger.error('Assign driver to shift error:', error);
      return res.status(error.statusCode || 500).json({ success: false, message: error.message || 'Phân công tài xế thất bại' });
    }
  }

  static async assignVehicle(req, res, _next) {
    try {
      const assignment = await ShiftService.assignVehicle({ ...req.body, actorId: req.user?.userId });
      return res.status(201).json({ success: true, message: 'Phân công xe vào ca thành công', assignment });
    } catch (error) {
      logger.error('Assign vehicle to shift error:', error);
      return res.status(error.statusCode || 500).json({ success: false, message: error.message || 'Phân công xe thất bại' });
    }
  }

  static async assignTrip(req, res, _next) {
    try {
      const assignment = await ShiftService.assignTrip({ ...req.body, actorId: req.user?.userId });
      return res.status(201).json({ success: true, message: 'Phân công chuyến vào ca thành công', assignment });
    } catch (error) {
      logger.error('Assign trip to shift error:', error);
      return res.status(error.statusCode || 500).json({ success: false, message: error.message || 'Phân công chuyến thất bại' });
    }
  }
}
