import express from 'express';
import ShiftController from './ShiftController.js';
import SchedulingController from './SchedulingController.js';
import RosterController from './RosterController.js';

const router = express.Router();

router.get('/rosters/weekly', RosterController.get);
router.get('/rosters/available-staff', RosterController.availableStaff);
router.get('/rosters/requirements', RosterController.requirements);
router.put('/rosters/requirements', RosterController.saveRequirements);
router.delete('/rosters/requirements', RosterController.resetRequirements);
router.post('/rosters/auto-generate', RosterController.autoGenerate);
router.post('/rosters/validate', RosterController.validate);
router.post('/rosters/publish', RosterController.publish);
router.post('/rosters/reopen', RosterController.reopen);
router.delete('/rosters/weekly', RosterController.cancelAll);

router.get('/scheduling/overview', SchedulingController.overview);
router.get('/scheduling/staffing-demand', SchedulingController.staffingDemand);
router.get('/scheduling/route-configs', SchedulingController.listConfigs);
router.put('/scheduling/route-configs', SchedulingController.saveConfigs);
router.get('/scheduling/eligible-drivers', SchedulingController.eligibleDrivers);
router.post('/scheduling/generate', SchedulingController.generate);
router.get('/scheduling/plans', SchedulingController.listPlans);
router.delete('/scheduling/plans/:planId', SchedulingController.cancelPlan);
router.post('/scheduling/validate', SchedulingController.validate);
router.post('/scheduling/confirm', SchedulingController.confirm);

router.get('/shifts', ShiftController.listShifts);
router.post('/shifts', ShiftController.createShift);
router.post('/shifts/auto-generate', ShiftController.autoGenerateDailySchedule);
router.post('/shifts/confirm-generated', ShiftController.confirmGeneratedShifts);
router.get('/shifts/trip-allocation/preview', ShiftController.previewTripAllocation);
router.post('/shifts/trip-allocation/confirm', ShiftController.confirmTripAllocation);
router.get('/trip-schedules/:tripId/available-drivers', ShiftController.tripAvailableDrivers);
router.post('/trip-schedules/:tripId/assign-driver', ShiftController.assignDriverToTrip);
router.delete('/trip-schedules/:tripId/driver-assignment', ShiftController.removeDriverFromTrip);
router.get('/shifts/available-drivers', ShiftController.listAvailableDrivers);
router.get('/shifts/available-assistants', ShiftController.listAvailableAssistants);
router.get('/shifts/available-vehicles', ShiftController.listAvailableVehicles);
router.post('/shifts/:shiftId/assign-driver', ShiftController.assignDriverToSelectedShift);
router.delete('/shifts/:shiftId/driver-assignment', ShiftController.removeDriverFromSelectedShift);
router.post('/shifts/:shiftId/assign-assistant', ShiftController.assignAssistantToSelectedShift);
router.delete('/shifts/:shiftId/assistant-assignment', ShiftController.removeAssistantFromSelectedShift);
router.post('/shifts/:shiftId/assign-vehicle', ShiftController.assignVehicleToSelectedShift);
router.post('/shifts/:shiftId/assign-trip', ShiftController.assignTripToSelectedShift);
router.get('/shifts/:shiftId/assignments', ShiftController.listShiftAssignments);
router.put('/shifts/:shiftId', ShiftController.updateShift);
router.delete('/shifts', ShiftController.archiveShifts);
router.delete('/shifts/:shiftId', ShiftController.archiveShift);
router.get('/shift-assignments', ShiftController.listAssignments);
router.get('/shift-audit-logs', ShiftController.listAuditLogs);
router.post('/shift-assignments/drivers', ShiftController.assignDriver);
router.post('/shift-assignments/vehicles', ShiftController.assignVehicle);
router.post('/shift-assignments/trips', ShiftController.assignTrip);

export default router;
